<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReferencePerformanceTargetElementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      \DB::table('reference_performance_target_element')->insert([
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Tersusunnya perencanaan perangkat pembelajaran/ bimbingan: action plan, silabus, RPP/RPL, bahan dan administrasi mengajar',
              'activity_item'                       => 'Menyusun Perangkat Pembelajaran Guru: Action Plan (Analisis Minggu Efektif, Prota, Promes)',
              'yield_unit'                          => 'Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perencanaan pembelajaran',
              'quality'                             => 'Capaian persentase penyusunan dokumen perencanaan pembelajaran',
              'time'                                => 'Waktu penyelesaian dokumen perencanaan pembelajaran',
              'code'                                => 1
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Tersusunnya perencanaan perangkat pembelajaran/ bimbingan: action plan, silabus, RPP/RPL, bahan dan administrasi mengajar',
              'activity_item'                       => 'Mengembangkan silabus, rencana pelaksanaan pembelajaran (RPP), dan bahan mengajar',
              'yield_unit'                          => 'Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perencanaan pembelajaran',
              'quality'                             => 'Capaian persentase penyusunan dokumen perencanaan pembelajaran',
              'time'                                => 'Waktu penyelesaian dokumen perencanaan pembelajaran',
              'code'                                => 2
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Tersusunnya perencanaan perangkat pembelajaran/ bimbingan: action plan, silabus, RPP/RPL, bahan dan administrasi mengajar',
              'activity_item'                       => 'Menyusun action plan dan rencana pelaksanaan layanan (RPL)',
              'yield_unit'                          => 'Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perencanaan pembelajaran',
              'quality'                             => 'Capaian persentase penyusunan dokumen perencanaan pembelajaran',
              'time'                                => 'Waktu penyelesaian dokumen perencanaan pembelajaran',
              'code'                                => 3
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Tersusunnya perencanaan perangkat pembelajaran/ bimbingan: action plan, silabus, RPP/RPL, bahan dan administrasi mengajar',
              'activity_item'                       => 'Menyusun administrasi guru lainnya (daftar hadir siswa, jurnal mengajar, catatan karakter siswa)',
              'yield_unit'                          => 'Daftar Hadir',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perencanaan pembelajaran',
              'quality'                             => 'Capaian persentase penyusunan dokumen perencanaan pembelajaran',
              'time'                                => 'Waktu penyelesaian dokumen perencanaan pembelajaran',
              'code'                                => 4
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya pembelajaran/ bimbingan sesuai dengan kondisi terkini (luring & daring), dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Melaksanakan pembelajaran sesuai kondisi luring maupun daring',
              'yield_unit'                          => 'PKG; Jurnal',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen pelaksanaan mengajar berupa Penilaian Kinerja Guru (PKG) dan jurnal mengajar',
              'quality'                             => 'Capaian persentase pelaksanaan pembelajaran (jumlah pertemuan)',
              'time'                                => 'Waktu pelaksanaan pembelajaran',
              'code'                                => 5
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya pembelajaran/ bimbingan sesuai dengan kondisi terkini (luring & daring), dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Melaksanakan kegiatan layanan bimbingan konseling sesuai kondisi terkini (luring/daring)',
              'yield_unit'                          => 'PKG; Jurnal',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen pelaksanaan mengajar berupa Penilaian Kinerja Guru (PKG) dan jurnal mengajar',
              'quality'                             => 'Capaian persentase pelaksanaan pembelajaran (jumlah pertemuan)',
              'time'                                => 'Waktu pelaksanaan pembelajaran',
              'code'                                => 6
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya penilaian hasil pembelajaran/ bimbingan sesuai kondisi luring maupun daring, dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Melaksanakan penilaian proses dan formatif dalam pembelajaran',
              'yield_unit'                          => 'Daftar Nilai',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen penilaian hasil pembelajaran',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian pembelajaran yang akuntabel',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya penilaian hasil pembelajaran',
              'code'                                => 7
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya penilaian hasil pembelajaran/ bimbingan sesuai kondisi luring maupun daring, dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Menyusun soal praktik, ulangan harian',
              'yield_unit'                          => 'Soal',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen penilaian hasil pembelajaran',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian pembelajaran yang akuntabel',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya penilaian hasil pembelajaran',
              'code'                                => 8
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya penilaian hasil pembelajaran/ bimbingan sesuai kondisi luring maupun daring, dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Menilai dan mengevaluasi proses dan hasil belajar pada mata pelajaran',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen penilaian hasil pembelajaran',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian pembelajaran yang akuntabel',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya penilaian hasil pembelajaran',
              'code'                                => 9
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya penilaian hasil pembelajaran/ bimbingan sesuai kondisi luring maupun daring, dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Menyusun alat ukur penilaian layanan bimbingan konseling',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen penilaian hasil pembelajaran',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian pembelajaran yang akuntabel',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya penilaian hasil pembelajaran',
              'code'                                => 10
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya penilaian hasil pembelajaran/ bimbingan sesuai kondisi luring maupun daring, dengan memanfaatkan media pembelajaran',
              'activity_item'                       => 'Menilai dan mengevaluasi proses hasil layanan bimbingan',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen penilaian hasil pembelajaran',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian pembelajaran yang akuntabel',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya penilaian hasil pembelajaran',
              'code'                                => 11
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya analisis hasil penilaian pembelajaran/ pembimbingan',
              'activity_item'                       => 'Melaksanakan analisis hasil penilaian pembelajaran',
              'yield_unit'                          => 'Analisis',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen analisis hasil penilaian',
              'quality'                             => 'Capaian persentase penyusunan dokumen analisis hasil penilaian mata pelajaran',
              'time'                                => 'Waktu yang diperlukan untuk penyusunan analisis hasil penilaian hasil',
              'code'                                => 12
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya analisis hasil penilaian pembelajaran/ pembimbingan',
              'activity_item'                       => 'Menganalisis hasil penilaian layanan bimbingan konseling',
              'yield_unit'                          => 'Analisis',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen analisis hasil penilaian',
              'quality'                             => 'Capaian persentase penyusunan dokumen analisis hasil penilaian mata pelajaran',
              'time'                                => 'Waktu yang diperlukan untuk penyusunan analisis hasil penilaian hasil',
              'code'                                => 13
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya tindak lanjut hasil penilaian pembelajaran/ pembimbingan',
              'activity_item'                       => 'Melaksanakan tindak lanjut berupa kegiatan perbaikan dan pengayaan berdasarkan hasil analisis penilaian pembelajaran',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perbaikan/pengayaan',
              'quality'                             => 'Capaian persentase pelaksanaan kegiatan tindak lanjut perbaikan/pengayaan',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya tindak lanjut',
              'code'                                => 14
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Isi, Kelulusan, Proses, dan Penilaian pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya tindak lanjut hasil penilaian pembelajaran/ pembimbingan',
              'activity_item'                       => 'Membuat laporan pelaksanaan program bimbingan',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen perbaikan/pengayaan',
              'quality'                             => 'Capaian persentase pelaksanaan kegiatan tindak lanjut perbaikan/pengayaan',
              'time'                                => 'Waktu yang diperlukan untuk terlaksananya tindak lanjut',
              'code'                                => 15
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas yang diberikan kepala sekolah dalam implementasi tugas tambahan sebagai wakil kepala sekolah',
              'activity_item'                       => 'Melaksanakan tugas tambahan sebagai wakil kepala sekolah',
              'yield_unit'                          => 'PKWKS; Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen administrasi tugas wakil kepala sekolah dan laporan penilaian kinerja wakil kepala sekolah',
              'quality'                             => 'Capaian persentase pelaksanaan tugas tambahan sebagai waka',
              'time'                                => 'Waktu pelaksanaan tugas tambahan sebagai waka',
              'code'                                => 16
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas yang diberikan kepala sekolah dalam implementasi tugas tambahan sebagai kepala program keahlian/studi',
              'activity_item'                       => 'Melaksanakan tugas tambahan sebagai ketua program keahlian/studi',
              'yield_unit'                          => 'PKK-prodi; Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen administrasi tugas kaprodi dan laporan penilaian kinerja kepala program studi',
              'quality'                             => 'Capaian persentase pelaksanaan tugas tambahan sebagai kaprodi',
              'time'                                => 'Waktu pelaksanaan tugas tambahan sebagai kaprodi',
              'code'                                => 17
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas yang diberikan kepala sekolah dalam implementasi tugas tambahan sebagai kepala perpustakaan',
              'activity_item'                       => 'Melaksanakan tugas tambahan sebagai kepala perpustakaan',
              'yield_unit'                          => 'PKK-pus; Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen administrasi tugas kepala perpustakaan dan laporan penilaian kinerja kepala perpustakaan',
              'quality'                             => 'Capaian persentase pelaksanaan tugas kepala perpustakaan',
              'time'                                => 'Waktu pelaksanaan tugas kepala perpustakaan',
              'code'                                => 18
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas yang diberikan kepala sekolah dalam implementasi tugas tambahan sebagai kepala laboratorium/bengkel/unit produksi',
              'activity_item'                       => 'Melaksanakan tugas tambahan sebagai kepala laboratorium/bengkel/unit produksi',
              'yield_unit'                          => 'PKK-lab; Dokumen',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen administrasi tugas kepala laboratorium dan laporan penilaian kinerja kepala laboratorium',
              'quality'                             => 'Capaian persentase pelaksanaan tugas kepala laboratorium',
              'time'                                => 'Waktu pelaksanaan tugas kepala laboratorium',
              'code'                                => 19
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas tambahan sebagai pembimbing khusus penyelenggara pendidikan inklusi/terpadu',
              'activity_item'                       => 'Melaksanakan tugas tambahan sebagai pembimbing khusus penyelenggara pendidikan inklusi/terpadu',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen',
              'quality'                             => 'Capaian persentase',
              'time'                                => 'Waktu pelaksanaan',
              'code'                                => 20
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas yang diberikan kepala sekolah dalam implementasi tugas sebagai sebagai wali kelas',
              'activity_item'                       => 'Melaksanakan tugas sebagai wali kelas',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen laporan pelaksanaan tugas sebagai wali kelas',
              'quality'                             => 'Capaian persentase tugas sebagai wali kelas',
              'time'                                => 'Waktu pelaksanaan sebagai wali kelas',
              'code'                                => 21
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas dalam menyusun kurikulum pada satuan pendidikan',
              'activity_item'                       => 'Melaksanakan tugas dalam menyusun kurikulum pada satuan pendidikan',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen kurikulum yang tersusun',
              'quality'                             => 'Capaian persentase penyusunan dokumen kurikulum',
              'time'                                => 'Waktu pelaksanaan penyusunan dokumen kurikulum',
              'code'                                => 22
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas dalam mengawasi penilaian dan evaluasi terhadap proses dan hasil belajar',
              'activity_item'                       => 'Melaksanakan tugas menjadi pengawas penilaian dan evaluasi terhadap proses dan hasil belajar',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen dalam menjalankan tugas menjadi pengawas penilaian tengah/akhir semester',
              'quality'                             => 'Capaian persentase dalam menjalankan tugas menjadi pengawas penilaian',
              'time'                                => 'Waktu pelaksanaan menjadi pengawas penilaian',
              'code'                                => 23
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas membimbing guru pemula dalam program induksi',
              'activity_item'                       => 'Melaksanakan bimbingan bagi guru pemula dalam program induksi.',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen laporan bimbingan guru pemula',
              'quality'                             => 'Capaian persentase penginduksian dalam membimbing guru pemula',
              'time'                                => 'Waktu pelaksanaan bimbingan guru pemula',
              'code'                                => 24
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas membimbing siswa dalam kegiatan ekstrakurikuler',
              'activity_item'                       => 'Membimbing siswa dalam kegiatan ekstrakurikuler.',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen laporan kegiatan ekstrakurikuler',
              'quality'                             => 'Capaian persentase pelaksanaan bimbingan dan pendampingan ekstrakurikuler',
              'time'                                => 'Waktu pelaksanaan bimbingan dan pendampingan ekstrakurikuler',
              'code'                                => 25
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas dalam bimbingan pada penyusunan publikasi ilmiah dan karya inovatif',
              'activity_item'                       => 'Melaksanakan tugas menjadi pembimbing pada penyusunan publikasi ilmiah dan karya inovatif guru',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen laporan pembimbingan pada penyusunan publikasi ilmiah dan karya inovatif guru',
              'quality'                             => 'Capaian persentase pelaksanaan pembimbingan penyusunan publikasi ilmiah dan karya inovatif',
              'time'                                => 'Waktu pelaksanaan pembimbingan penyusunan publikasi ilmiah dan karya inovatif',
              'code'                                => 26
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan tugas kepemimpinan atau manajerial sekolah dalam pengelolaan dan pelaksanaan pembelajaran di sekolah',
              'performance_plan'                         => 'Terlaksananya tugas pembimbingan pada kelas yang menjadi tanggung jawabnya sebagai guru kelas',
              'activity_item'                       => 'Melaksanakan pembimbingan pada kelas yang menjadi tanggung jawabnya sebagai guru kelas',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => NULL,
              'quantity'                            => 'Jumlah dokumen laporan pembimbingan sebagai guru kelas mencakup catatan karakter dan perilaku peserta didik',
              'quality'                             => 'Capaian persentase pembimbingan pada kelas',
              'time'                                => 'Waktu pelaksanaan pembimbingan kelas',
              'code'                                => 27
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional lebih dari 960 jam',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 15,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 28
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional antara 641 s.d. 960 jam',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 9,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 29
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional antara 481 s.d. 640 jam',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 6,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 30
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional antara 181 s.d. 480 jam',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 31
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional antara 81 s.d. 180 jam.',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 32
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan diklat fungsional antara 30 s.d. 80 jam.',
              'yield_unit'                          => 'Sertifikat; Laporan',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 33
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan lokakarya penyusunan perangkat kurikulum dan atau pembelajaran',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.15,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 34
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Pemateri kegiatan ilmiah berupa seminar, kologium, atau diskusi panel',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.2,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 35
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Peserta kegiatan ilmiah berupa seminar, kologium, atau diskusi panel',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.1,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 36
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Kegiatan Pengembangan Diri dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan kegiatan kolektif yang sesuai dengan tugas dan kewajiban guru',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.1,
              'quantity'                            => 'Jumlah dokumen pelaksanaan pengembangan diri (sertifikat, surat tugas, undangan, dan laporan)',
              'quality'                             => 'Capaian persentase pelaksanaan keikutsertaan kegiatan yang dimaksud',
              'time'                                => 'Waktu tercapainya pelaksanaan kegiatan yang dimaksud',
              'code'                                => 37
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Narasumber pada presentasi seminar atau lokakarya ilmiah',
              'yield_unit'                          => 'Makalah Ilmiah',
              'credit_score'                        => 0.2,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 38
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Narasumber pada presentasi koloqium atau diskusi ilmiah',
              'yield_unit'                          => 'Makalah Ilmiah',
              'credit_score'                        => 0.2,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 39
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku penelitian pendidikan di sekolah, dipublikasikan (ber ISBN) dan lulus penilaian BNSP',
              'yield_unit'                          => 'Buku Penelitian',
              'credit_score'                        => 4,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 40
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan karya tulis ilmiah pendidikan, terbit dalam jurnal ilmiah tingkat nasional terakreditasi',
              'yield_unit'                          => 'Jurnal Ilmiah',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 41
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan karya tulis ilmiah pendidikan, terbit dalam jurnal ilmiah tingkat provinsi',
              'yield_unit'                          => 'Jurnal Ilmiah',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 42
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan karya tulis ilmiah pendidikan, terbit dalam jurnal ilmiah tingkat kabupaten/kota',
              'yield_unit'                          => 'Jurnal Ilmiah',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 43
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan Penelitian Tindakan Kelas (PTK), diseminarkan di sekolah dan disimpan di perpustakaan',
              'yield_unit'                          => 'PTK',
              'credit_score'                        => 4,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 44
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan makalah ilmiah pendidikan/pembelajaran, tidak diterbitkan, disimpan di perpustakaan',
              'yield_unit'                          => 'Makalah Ilmiah',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 45
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan artikel ilmiah populer bidang pendidikan formal, dimuat di media masa tingkat nasional',
              'yield_unit'                          => 'Artikel Populer',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 46
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan artikel ilmiah populer bidang pendidikan formal, dimuat di koran daerah',
              'yield_unit'                          => 'Artikel Populer',
              'credit_score'                        => 1.5,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 47
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan artikel ilmiah populer bidang pendidikan formal, dimuat di tingkat lokal',
              'yield_unit'                          => 'Artikel Populer',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 48
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku pelajaran yang lolos penilaian oleh BSNP',
              'yield_unit'                          => 'Buku Pelajaran',
              'credit_score'                        => 6,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 49
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku pelajaran yang dicetak penerbit dan ber ISBN',
              'yield_unit'                          => 'Buku Pelajaran',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 50
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku pelajaran yang dicetak penerbit belum ber ISBN',
              'yield_unit'                          => 'Buku Pelajaran',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 51
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan modul/diktat pembelajaran, digunakan di tingkat provinsi dan disahkan Dinas Pendidikan',
              'yield_unit'                          => 'Modul',
              'credit_score'                        => 1.5,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 52
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan modul/diktat pembelajaran, digunakan di tingkat kabupaten dan disahkan Dinas Pendidikan',
              'yield_unit'                          => 'Modul',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 53
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan modul/diktat pembelajaran, digunakan di tingkat sekolah',
              'yield_unit'                          => 'Modul',
              'credit_score'                        => 0.5,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 54
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku bidang pendidikan dicetak oleh penerbit dan ber ISBN',
              'yield_unit'                          => 'Buku',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 55
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku bidang pendidikan dicetak oleh penerbit dan belum ber ISBN',
              'yield_unit'                          => 'Buku',
              'credit_score'                        => 1.5,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 56
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan karya terjemahan yang dinyatakan oleh kepala sekolah',
              'yield_unit'                          => 'Karya Terjemahan',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 57
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Publikasi Ilmiah dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan pembuatan buku pedoman guru',
              'yield_unit'                          => 'Buku Pedoman Guru',
              'credit_score'                        => 1.5,
              'quantity'                            => 'Jumlah dokumen publikasi ilmiah berupa buku, jurnal/artikel/makalah ilmiah, modul/diktat, ataupun PTK.',
              'quality'                             => 'Capaian persentase penyusunan dokumen publikasi ilmiah',
              'time'                                => 'Waktu pelaksanaan penyelesaian dokumen publikasi ilmiah',
              'code'                                => 58
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Menemukan teknologi tepat guna kategori kompleks',
              'yield_unit'                          => 'Karya',
              'credit_score'                        => 4,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 59
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Menemukan teknologi tepat guna kategori sederhana',
              'yield_unit'                          => 'Karya',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 60
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Menciptakan karya seni kategori kompleks',
              'yield_unit'                          => 'Karya',
              'credit_score'                        => 4,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 61
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Menciptakan karya seni kategori sederhana',
              'yield_unit'                          => 'Karya',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 62
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Membuat alat pelajaran/peraga/praktikum kategori kompleks',
              'yield_unit'                          => 'Alat',
              'credit_score'                        => 4,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 63
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Membuat alat pelajaran/peraga/praktikum kategori sederhana',
              'yield_unit'                          => 'Alat',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 64
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan penyusunan standar/pedoman/soal tingkat nasional',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 65
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Pengelolaan Standar Pendidik dan Tenaga Kependidikan pada 8 Standar Nasional Pendidikan',
              'performance_plan'                         => 'Terlaksananya Pembuatan Karya Inovatif dalam Pengembangan Keprofesian Berkelanjutan (PKB) Guru',
              'activity_item'                       => 'Melaksanakan penyusunan standar/pedoman/soal tingkat provinsi',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen karya inovatif yang dihasilkan dalam rangka pengembangan keprofesian berkelanjutan.',
              'quality'                             => 'Capaian persentase hasil pelaksanaan pembuatan karya inovatif',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam pembuatan karya inovatif',
              'code'                                => 66
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Peningkatan kualifikasi SDM pendidik dan tenaga kependidikan',
              'performance_plan'                         => 'Terlaksananya peningkatan kualifikasi pendidikan dengan gelar kesarjanaan, magister, maupun doktoral',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang Doktoral [S3]',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 200,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'quality'                             => 'Capaian persentase gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 67
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Peningkatan kualifikasi SDM pendidik dan tenaga kependidikan',
              'performance_plan'                         => 'Terlaksananya peningkatan kualifikasi pendidikan dengan gelar kesarjanaan, magister, maupun doktoral',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang Magister [S2]',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 150,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'quality'                             => 'Capaian persentase gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 68
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Peningkatan kualifikasi SDM pendidik dan tenaga kependidikan',
              'performance_plan'                         => 'Terlaksananya peningkatan kualifikasi pendidikan dengan gelar kesarjanaan, magister, maupun doktoral',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang kesarjanaan [S1/Diploma IV]',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 100,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'quality'                             => 'Capaian persentase gelar kesarjanaan, magister, ataupun doktoral yang diperoleh',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 69
          ],
          [
              'element'                             => 'KINERJA UTAMA',
              'direct_supervisor_performance_plan'  => 'Peningkatan kualifikasi SDM pendidik dan tenaga kependidikan',
              'performance_plan'                         => 'Terlaksananya pelatihan kedinasan serta memperoleh surat tanda tamat pendidikan dan pelatihan',
              'activity_item'                       => 'Melaksanakan pelatihan prajabatan fungsional bagi calon pegawai negeri sipil dan program induksi',
              'yield_unit'                          => 'STTPL',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah surat tanda tamat pendidikan dan pelatihan',
              'quality'                             => 'Capaian persentase kualitas pelatihan prajabatan dan program guru induks',
              'time'                                => 'Waktu yang diperlukan dalam pelatihan prajabatan dan program induksi',
              'code'                                => 70
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan peningkatan kualifikasi pendidikan umum bagi guru dan tenaga kependidikan',
              'performance_plan'                         => 'Tercapainya gelar lain yang tidak sesuai dengan bidangnya',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang doktoral (S3) yang tidak sesuai dengan bidangnya',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 15,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang tidak sesuai bidangnya',
              'quality'                             => 'Capaian persentase gelar yang diperoleh dan tidak sesuai bidangnya',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 71
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan peningkatan kualifikasi pendidikan umum bagi guru dan tenaga kependidikan',
              'performance_plan'                         => 'Tercapainya gelar lain yang tidak sesuai dengan bidangnya',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang magister (S2), yang tidak sesuai dengan bidangnya',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 10,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang tidak sesuai bidangnya',
              'quality'                             => 'Capaian persentase gelar yang diperoleh dan tidak sesuai bidangnya',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 72
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan peningkatan kualifikasi pendidikan umum bagi guru dan tenaga kependidikan',
              'performance_plan'                         => 'Tercapainya gelar lain yang tidak sesuai dengan bidangnya',
              'activity_item'                       => 'Melaksanakan pendidikan jenjang kesarjanaan (S1/Diploma IV), yang tidak sesuai dengan bidangnya',
              'yield_unit'                          => 'Ijazah',
              'credit_score'                        => 5,
              'quantity'                            => 'Jumlah gelar kesarjanaan, magister, ataupun doktoral yang tidak sesuai bidangnya',
              'quality'                             => 'Capaian persentase gelar yang diperoleh dan tidak sesuai bidangnya',
              'time'                                => 'Waktu pelaksanaan yang diperlukan dalam memperoleh gelar',
              'code'                                => 73
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'performance_plan'                         => 'Terlaksananya kegiatan yang mendukung tugas guru sebagai pengawas ujian',
              'activity_item'                       => 'Melaksanakan tugas sebagai pengawas Ujian Sekolah tahun pelajaran 2020/2021',
              'yield_unit'                          => 'SK',
              'credit_score'                        => 0.08,
              'quantity'                            => 'Jumlah dokumen pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'quality'                             => 'Capaian persentase pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'time'                                => 'Waktu yang diperlukan untuk mencapai pelaksanaan kegiatan yang mendukung tugas',
              'code'                                => 74
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'performance_plan'                         => 'Terlaksananya kegiatan yang mendukung tugas guru sebagai pengawas ujian',
              'activity_item'                       => 'Melaksanakan tugas sebagai pengawas Asesmen Nasional Berbasis Komputer tahun pelajaran 2021/2022',
              'yield_unit'                          => 'SK',
              'credit_score'                        => 0.08,
              'quantity'                            => 'Jumlah dokumen pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'quality'                             => 'Capaian persentase pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'time'                                => 'Waktu yang diperlukan untuk mencapai pelaksanaan kegiatan yang mendukung tugas',
              'code'                                => 75
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'performance_plan'                         => 'Terlaksananya kegiatan yang mendukung tugas guru sebagai pengawas ujian',
              'activity_item'                       => 'Melaksanakan tugas sebagai pengawas Seleksi CASN PPPK',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.08,
              'quantity'                            => 'Jumlah dokumen pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'quality'                             => 'Capaian persentase pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'time'                                => 'Waktu yang diperlukan untuk mencapai pelaksanaan kegiatan yang mendukung tugas',
              'code'                                => 76
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'performance_plan'                         => 'Terlaksananya bimbingan siswa dalam praktik kerja atau ekstrakurikuler atau sejenisnya',
              'activity_item'                       => 'Melaksanakan bimbingan siswa dalam praktik kerja',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.17,
              'quantity'                            => 'Jumlah dokumen pelaksanaan bimbingan praktik kerja, ekstrakurikuler, atau sejenisnya',
              'quality'                             => 'Capaian persentasepelaksanaan bimbingan siswa',
              'time'                                => 'Waktu yang diperlukan dalam pelaksanaan bimbingan siswa',
              'code'                                => 77
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Pelaksanaan kegiatan yang mendukung tugas sebagai guru',
              'performance_plan'                         => 'Terlaksananya bimbingan siswa dalam praktik kerja atau ekstrakurikuler atau sejenisnya',
              'activity_item'                       => 'Melaksanakan bimbingan siswa dalam persiapan lomba',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.17,
              'quantity'                            => 'Jumlah dokumen pelaksanaan bimbingan praktik kerja, ekstrakurikuler, atau sejenisnya',
              'quality'                             => 'Capaian persentasepelaksanaan bimbingan siswa',
              'time'                                => 'Waktu yang diperlukan dalam pelaksanaan bimbingan siswa',
              'code'                                => 78
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan organisasi profesi yang mendukung tugas guru',
              'performance_plan'                         => 'Mengikuti kegiatan organisasi profesi yang mendukung tugas guru',
              'activity_item'                       => 'Aktif sebagai pengurus dalam kegiatan organisasi profesi',
              'yield_unit'                          => 'KTA',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen kegiatan organisasi profesi yang diikuti',
              'quality'                             => 'Capaian persentase kegiatan organisasi profesi yang diikuti',
              'time'                                => 'Waktu pelaksanaan kegiatan organisasi profesi yang diikuti',
              'code'                                => 79
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan organisasi profesi yang mendukung tugas guru',
              'performance_plan'                         => 'Mengikuti kegiatan organisasi profesi yang mendukung tugas guru',
              'activity_item'                       => 'Aktif sebagai anggota dalam kegiatan organisasi profesi',
              'yield_unit'                          => 'KTA',
              'credit_score'                        => 0.75,
              'quantity'                            => 'Jumlah dokumen kegiatan organisasi profesi yang diikuti',
              'quality'                             => 'Capaian persentase kegiatan organisasi profesi yang diikuti',
              'time'                                => 'Waktu pelaksanaan kegiatan organisasi profesi yang diikuti',
              'code'                                => 80
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan dalam lingkup pendidikan yang mendukung tugas guru',
              'performance_plan'                         => 'Mengikuti kegiatan kepramukaan',
              'activity_item'                       => 'Menjadi pengurus aktif kegiatan kepramukaan',
              'yield_unit'                          => 'KTA',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen keanggotaan kegiatan kepramukaan',
              'quality'                             => 'Capaian persentase keikutsertan kegiatan kepramukaan',
              'time'                                => 'Waktu masa pelaksanaan kegiatan kepramukaan',
              'code'                                => 81
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan dalam lingkup pendidikan yang mendukung tugas guru',
              'performance_plan'                         => 'Mengikuti kegiatan kepramukaan',
              'activity_item'                       => 'Menjadi anggota aktif kegiatan kepramukaan',
              'yield_unit'                          => 'KTA',
              'credit_score'                        => 0.75,
              'quantity'                            => 'Jumlah dokumen keanggotaan kegiatan kepramukaan',
              'quality'                             => 'Capaian persentase keikutsertan kegiatan kepramukaan',
              'time'                                => 'Waktu masa pelaksanaan kegiatan kepramukaan',
              'code'                                => 82
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan dalam lingkup pendidikan yang mendukung tugas guru',
              'performance_plan'                         => 'Melaksanakan kegiatan yang mendukung tugas guru dalam lingkup pendidikan',
              'activity_item'                       => 'Menjadi anggota Tim Penilai Angka Kredit',
              'yield_unit'                          => 'Laporan',
              'credit_score'                        => 0.04,
              'quantity'                            => 'Jumlah dokumen keanggotaan dan keterangan daftar usul Penilaian Angka Kredit yang dinilai olehnya',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian angka kredit',
              'time'                                => 'Waktu diperlukan untuk menyelesaikan penilaian angka kredit',
              'code'                                => 83
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Partisipasi kegiatan dalam lingkup pendidikan yang mendukung tugas guru',
              'performance_plan'                         => 'Melaksanakan kegiatan yang mendukung tugas guru dalam lingkup pendidikan',
              'activity_item'                       => 'Melaksanakan kegiatan menjadi tutor/pelatih/instruktur',
              'yield_unit'                          => 'Lap. Jadwal',
              'credit_score'                        => 0.04,
              'quantity'                            => 'Jumlah dokumen keanggotaan dan keterangan daftar usul Penilaian Angka Kredit yang dinilai olehnya',
              'quality'                             => 'Capaian persentase pelaksanaan penilaian angka kredit',
              'time'                                => 'Waktu diperlukan untuk menyelesaikan penilaian angka kredit',
              'code'                                => 84
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Perolehan penghargaan atau tanda jasa',
              'performance_plan'                         => 'Memperoleh penghargaan atau tanda jasa satya lancana karya satya',
              'activity_item'                       => 'Memperoleh penghargaan tanda jasa satya lancana karya satya 30 tahun',
              'yield_unit'                          => 'Piagam',
              'credit_score'                        => 3,
              'quantity'                            => 'Jumlah dokumen penghargaan tanda pengabdian selama kurun waktu tertentu',
              'quality'                             => 'Capaian persentase penghargaan yang diberikan',
              'time'                                => 'Waktu yang diperlukan dalam mendapatkan penghargaan',
              'code'                                => 85
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Perolehan penghargaan atau tanda jasa',
              'performance_plan'                         => 'Memperoleh penghargaan atau tanda jasa satya lancana karya satya',
              'activity_item'                       => 'Memperoleh penghargaan tanda jasa satya lancana karya satya 20 tahun',
              'yield_unit'                          => 'Piagam',
              'credit_score'                        => 2,
              'quantity'                            => 'Jumlah dokumen penghargaan tanda pengabdian selama kurun waktu tertentu',
              'quality'                             => 'Capaian persentase penghargaan yang diberikan',
              'time'                                => 'Waktu yang diperlukan dalam mendapatkan penghargaan',
              'code'                                => 86
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Perolehan penghargaan atau tanda jasa',
              'performance_plan'                         => 'Memperoleh penghargaan atau tanda jasa satya lancana karya satya',
              'activity_item'                       => 'Memperoleh penghargaan tanda jasa satya lancana karya satya 10 tahun',
              'yield_unit'                          => 'Piagam',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen penghargaan tanda pengabdian selama kurun waktu tertentu',
              'quality'                             => 'Capaian persentase penghargaan yang diberikan',
              'time'                                => 'Waktu yang diperlukan dalam mendapatkan penghargaan',
              'code'                                => 87
          ],
          [
              'element'                             => 'KINERJA TAMBAHAN',
              'direct_supervisor_performance_plan'  => 'Perolehan penghargaan atau tanda jasa',
              'performance_plan'                         => 'Memperoleh penghargaan atau tanda jasa satya lancana karya satya',
              'activity_item'                       => 'Memperoleh penghargan tanda jasa',
              'yield_unit'                          => 'Piagam',
              'credit_score'                        => 1,
              'quantity'                            => 'Jumlah dokumen penghargaan tanda pengabdian selama kurun waktu tertentu',
              'quality'                             => 'Capaian persentase penghargaan yang diberikan',
              'time'                                => 'Waktu yang diperlukan dalam mendapatkan penghargaan',
              'code'                                => 88
          ]
      ]);
    }
}
